### ISSUE TITLE
Master thesis first draft

### ISSUE THREAD

**Issue by marianntlu** [TLU-Human-computer-interaction/masterThesis#11]
```[tasklist]
### Tasks
- [x] Redefine research questions
- [x] define basic structure of the thesis
- [ ] Inital information in most sections
- [ ] Plan for sections that are not written
```
